# fly.toml app configuration file generated for backend-purple-dream-570 on 2025-07-23T11:39:37+10:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'backend-purple-dream-570'
primary_region = 'syd'

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
